name: LoveSanjskaObleka
favicon: null
layout_spectrum: 0.26756
typography_spectrum: 0.38336
title: Wedding inspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#170b1f'
    - '#dc586f'
    - '#f3a100'
    - '#c1044a'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
