name: LoveSanjskaObleka
favicon: null
layout_spectrum: 0.15401074313558638
typography_spectrum: 0.9888754130806774
title: Wedding inspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
