name: LoveSanjskaObleka
favicon: null
layout_spectrum: 0.15401074313558638
typography_spectrum: 0.9888754130806774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.20771301188506186
  lightness: 0.15059641492553055
  saturation: 0.17662497190758586
  rhythmicContrast: 0.5087438386399299
purpose: []
